 tasks:                                                        #--------
          - name: install https server on hosts
            action: yum name='{{pkgname}}' state=installed      #task part
            notify: task done           #--------
          - name: add a list of user
            user: name='{{ item }}' state=present   #-----
            with_items:
                    -Raj
                    -Raheem
                    -Salman                        # looping part